wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 128
Dataset:
  desc: null
  value: data
Disc_config:
  desc: null
  value:
    res: 64
Discriminator:
  desc: null
  value: StyleGAN
Gen_config:
  desc: null
  value:
    deep_mapping: 8
    latent_size: 256
    res: 64
Generator:
  desc: null
  value: StyleGAN
IMG_SIZE:
  desc: null
  value: 64
Loss_config:
  desc: null
  value:
    lambda_gp: 10
Loss_disc:
  desc: null
  value: r1
Loss_gen:
  desc: null
  value: r1
Optim_D:
  desc: null
  value: RMSprop
Optim_D_config:
  desc: null
  value:
    alpha: 0.99
    lr: 0.0001
Optim_G:
  desc: null
  value: RMSprop
Optim_G_config:
  desc: null
  value:
    alpha: 0.99
    lr: 0.0001
Trainer:
  desc: null
  value: gp
UPD_FOR_GEN:
  desc: null
  value: 1
Weight_dir:
  desc: null
  value: weight\StyleGAN StyleGAN 64
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1681327539.177771
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.9.15
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
epochs:
  desc: null
  value: 100
wandb_set:
  desc: null
  value: true
z_dim:
  desc: null
  value: 256
